### PR TITLE
Update invite_trustee.text.erb

### PR DESCRIPTION
**Pull request by avicaplan**
Not sure if it is possible to send to awesome-web without being a member. In any case, do we really need contact information here?

### CODE REVIEW

**Comment by jcn** [comment]
Good point, but maybe we should include the webmaster@awesomefoundation.org email address which is public?

**Comment by avicaplan** [comment]
I don't really see a great need for contact or support information on this particular interaction... If anything, they should probably start by going to their Dean for help. So, happy to put the webmaster e-mail there if you want, but I don't think it's necessary.

**Comment by jcn** [comment]
Good call. What about just adding language about contacting their dean?

**Comment by avicaplan** [comment]
Sounds good! Unless it has to be localized? But possibly this is text that is not set up for localization?

**Comment by jcn** [comment]
It should be localized, but is not set up for it yet, so I'll be adding that as a new story to work on. Can you add the language and update the pull request?

**Pull request closed without merging**
