### PR TITLE
Update countries.rb

### PR DESCRIPTION
**Pull request by avicaplan**

### CODE REVIEW

**Comment by jcn** [comment]
@avicaplan I'm actually reverting this change, for 2 reasons:

1. This doesn't actually do anything. The country names all come from the `country_select` gem, so if we want to muck with country names, we should probably update this gem, which might cause a bunch of other things, so I want to do it mindfully
2. The names in the dropdown are the official ISO 3166-2 country names: https://en.wikipedia.org/wiki/ISO_3166-2 so we should talk about why, specifically, you want to make this change

**Comment by avicaplan** [comment]
Oops... this was the only place I found the names, so I took a guess they were coming from here! Not a big deal if it risks messing up other things, but we now have a DRC chapter and I think it may actually be named wrong in that listing -- in fact, when you click through on the country code in that list it takes you here: https://en.wikipedia.org/wiki/ISO_3166-2:CD. But like I said, not a big deal if it risks messing up other things.

**Comment by jcn** [comment]
It's definitely confusing. I have to see whether the section of code you edited is actually used at all and if not, it should probably be removed.

Understood about the chapter. I'll make a ticket to address that in the right place, and then we can see about making the change.

**Comment by jcn** [comment]
Added this ticket https://github.com/awesomefoundation/awesomebits/issues/278

**Pull request merged**
