### PR TITLE
custom tiled project gallery with lightbox

### PR DESCRIPTION
**Pull request by deadroxy**
Opening this new PR to reflect a solid v1.0 on the new tiled project gallery which fulfills the request from [issue 174](https://github.com/awesomefoundation/awesomebits/issues/174). In the series of commits for this first complete version you will see that:
- Old project gallery code (known as slideshow) has all been removed
- New lightbox ([lightgallery.js](https://github.com/sachinchoolur/lightgallery.js)) has been integrated into the codebase
- 5 partials holding each of the different tile layouts have been created
- Project image tile is now completely responsive, scaling smoothly through all viewport sizes
- Clicking on any image in the tile will open the lightbox
- Lightbox utilizes thumbnails alongside full size photos for faster loading
- Lightbox itself is responsive and allows for swipe on mobile
- Lightbox does not open on pages without real photos

I think it's looking pretty good already. We can obviously work out any kinks or make any tweaks, but I'd say this initial pass is 90% of the way there. We'll probably want to freshen up the tests to make them more relevant but I attempted to make sure they aren't broken. Let me know how it looks to you @jcn.

Screen Shot 2019-05-23 at 12 52 23 AM

### CODE REVIEW

**Comment by deadroxy** [comment]
Looks like some of the tests are failing after all. Like I said, we can fix these up together. I didn't want to delete all the tests, because I figured you'd actually want them to be updated. However, since we have a much more complex display logic than in the old version, I thought we ought to discuss what the tests should look like now.

**Comment by deadroxy** [comment]
Attaching a screenshot of the 5up tile on an iPhone 5S:

IMG_6260

**Comment by deadroxy** [comment]
With this almost-final pass the project is close to completion. Apart from improving the tests for this new image gallery, all other outstanding requests have been completed. This includes:
- Creating evenly spaced gutters between all images in the tile*
- Adding a view photos button in the lower right corner of the tile that launches the lightboxº
- Designing a custom CSS rollover animation to make the tiles bloop

*Note: this gutters are currently the same dark grey color as the border for the entire tile. This can be easily changed to white/transparent gutters and border if desired.

ºNote: For some reason, when launching the lightbox programmatically the swipe/scroll order exhibits an odd behavior. I could not find documentation or a logical reason for this. See the [commit message](https://github.com/awesomefoundation/awesomebits/pull/391/commits/c00fa3061c8074178d5712f055801c2989fa2e4b) for more info.

Here's a selection of images demonstrating the current look and feel:
Screen Shot 2019-05-25 at 12 49 41 AM
Screen Shot 2019-05-25 at 12 47 59 AM
Screen Shot 2019-05-25 at 12 47 46 AM
Screen Shot 2019-05-25 at 12 47 11 AM
Screen Shot 2019-05-25 at 12 46 51 AM
Screen Shot 2019-05-25 at 12 46 41 AM
Screen Shot 2019-05-25 at 12 46 35 AM

**Comment by deadroxy** [comment]
Also, fwiw, I wasn't exactly sure how to run the test suite in Docker. Here's how to do so if it's your first time:

`docker-compose run -e "RAILS_ENV=test" web bundle exec rake db:create`
`docker-compose run -e "RAILS_ENV=test" web bundle exec rake db:migrate`
`docker-compose run -e "RAILS_ENV=test" web bundle exec rake`

**Comment by jcn** [comment]
@deadroxy Overall this looks good! I need to address the failing tests still but I did notice that the image ordering in lightgallery is weird both when launching the gallery with the button (as discussed) but also when there are just 2 images, even when launching normally (by clicking on an image). I'll look at this more, but I wanted to check to see if you're seeing this behavior as well.

**Comment by jcn** [comment]
Looks great!

Closes #174 
Closes #100

**Comment by avicaplan** [comment]
I think we can probably now remove the following text from the application form, yes?

"The top image is set as the cover image. Images will be resized to 940x470 pixels. If you get an error message, please try again with fewer or smaller files."

**Comment by jcn** [comment]
Sure thing.

**Pull request merged**
