### PR TITLE
Gem upgrades

### PR DESCRIPTION
**Pull request by arsduo**
Next stop after Ruby 2.1: gem updates. This pull request upgrades all our gems to the newest version, with several exceptions:  
- rspec: there's a bit more to the RSpec 3 upgrade, I'll do that in a separate follow-up
- rails: Rails major version change, need I say more?
- flutie, jquery, jquery-ui: upgrading these breaks the UI

Test plan: this, more than the Ruby upgrade, carries risks that our incomplete test coverage could cause problems. I'll try to do some local testing this weekend and report on results if I can.

### CODE REVIEW

**Comment by jcn** [comment]
Are you planning on continuing the work on this PR, or should we close it and possibly try to do gem upgrades in smaller chunks?

**Comment by arsduo** [comment]
I think doing it in smaller chunks is a good idea -- can you assign it to me to close and open up some new ones? I'll try to hack on it later this week -- maybe see if I can convince Cedric to take some as well.

**Comment by jcn** [comment]
@arsduo It's assigned to you. Feel free to open up PRs as needed, or open a new issue as the "parent" to work off of. I don't really have a preference!

**Comment by arsduo** [comment]
Closing this. I'll issue new PRs for gem upgrades as I get them ready.

**Pull request closed without merging**
