### PR TITLE
#174, #100 Image gallery on project page

### LINKED ISSUE #100: Ensure the image scroller on the project page works in mobile
Related to issue #99.

On the project page, multiple images are not immediately obvious. In mobile view you can kind of quickly tap the image and then the next and previous buttons show up, but this is a weird and non-intuitive interface.

One solution is to just have the buttons show up all the time if there are multiple images to scroll through. This might actually be the best solution so it's obvious even in non-mobile views.

The other option is to make those next and previous buttons show up all the time in the mobile view only. 

In either case, those buttons should be positioned correctly - on the iPad at least the "previous" button is hanging a bit off the page to the left, though that might be just the whole page being centered incorrectly.

Opinions welcome.

### LINKED ISSUE #174: Better image display on funded project pages
The main problem here is that we ask for people to upload photos with a 2:1 aspect ratio, and the website is _only_ designed to display photos with that ratio. See for example the following:

screen shot 2018-06-22 at 4 47 31 pm

Above is what is displayed on this project page. 

The actual photo being uploaded however is:

trike_at_night

Since it seems clear that users are just going to upload images with non-conforming aspect ratios  there are a couple of ways of handling this:

- Handle the image gallery by loading full-sized images in a lightbox (_Using a lightbox interface should fix Issue #100 as well_)
- Provide a cropping interface for the "main" image that displays on the project page

or

- Provide a cropping interface for all of the images for a funded project only, since we display the original images in the application review process, and keep the layout of the project page the same as it currently is

or

- Redesign the project page to handle arbitrary image sizes, but I think that seems like a fight not worth fighting, and will probably require some sort of cropping interface anyway. 

Note: This project specifically does not involve the dashboard display of images which is Issue #173.

### PR DESCRIPTION
**Pull request by ilya-konanykhin**
In order to fix #174 and #100, I think the best we can do now is add a proper mobile-friendly image gallery. I propose using Fotorama (http://fotorama.io/). Despite it being unmaintained since the last year, it still has many benefits:

1. Time-proven solution, personally has been using it for many years, works like a charm
2. Rock-solid, well written
3. Very mobile friendly
4. Open-source
5. Has fullscreen mode
6. Can handle images with different aspects in one gallery (exactly what we need)

Please see the video I recorded with it locally: https://yadi.sk/i/WI9hSLM-3aD652

I kept in mind @jcn mentioned empty space looks weird. However, I still think we should deal with it: even if adding a cropping interface, some folks may skip cropping. Also, we have a lot of images already loaded — doubt anyone would go and properly re-crop them all?

Anyhow, if manual cropping is added in future (or we enforce automatic cropping, like we do now), the gallery will still work, just the empty space to the sides will disappear. So dark gray background is the worst case for "bad" images.

What do you think?

**Note 1** I added nav thumbnails, but they can be substituted with dots or removed completely.

**Note 2** The dark gray bgcolor is taken from the header.

**Note 3** Please do not review the code yet! This PR is WIP, opening to discuss visual changes. If you give it a go, I'll clean up and re-send.

af-174-100-desktop

af-174-100-mobile

Fixes #174, Fixes #100

### CODE REVIEW

**Comment by ilya-konanykhin** [comment]
PS: I've taken images with crazy width to height ratios to demonstrate the works case. Obviously, if all the images are 2/1, the gallery will look much better.

**Comment by spacemunkay** [comment]
Love the functionality!   Of course, @jcn has the final say, but here are my thoughts.

1. I'm okay using an outdated library.  If it's easy/familiar for you then great.  It's not like we're not using any other outdated libraries :)  And I think our frequency of updates is pretty low, so I doubt it will get touched again until we do a site overhaul.
1. I got the opinions of a few friends and aesthetically, they thought the black/grey background did make the site look a bit less professional ( I personally don't care, but I'm a biased & lazy engineer). However, the context did make a difference.  So, they were okay with it being on an individual project page given you have to drill down into it.  The most important thing is that we enforce the automatic cropping (2:1 ratio) on the [main page](www.awesomefoundation.org) and on the [chapter page](https://www.awesomefoundation.org/en/chapters/sf), like we do now.  So, I think this PR meets that requirement, using fotorama with a free aspect only for the project pages, then using fotorama with enforced cropping on the main & chapter pages.  That way, the main & chapter pages can carry more of the aesthetic appeal of the site. 
1. I like the nav thumbnails and prefer those instead of dots.  

@jcn, how do you feel about it?

**Comment by ilya-konanykhin** [comment]
> So, I think this PR meets that requirement, using fotorama with a free aspect only for the project pages, then using fotorama with enforced cropping on the main & chapter pages

Yeah, the idea was that if we can assure the images are properly cropped, all looks good (main and chapter pages receive personal care, think it is not that hard to maintain the proper aspect ratio there). And only old/inactive/ill maintained projects will get the background.

**Comment by jcn** [comment]
Thanks for the explanation about the decision making process. I still want to review this visually.

I see what @spacemunkay means when he got the comments about things looking "unprofessional" with the grey bars. Originally my thought was to have things work the way Airbnb works (see an example page like https://www.airbnb.com/rooms/49508) where the main image is always cropped but the rest of them open in a lightbox and you're always seeing things full-screen. That said, I also see the benefit of being able to scroll through images while you're just sitting on the page, so displaying the full image in the height of the scrollable area might make sense. 

Let me think about this one and solicit some other design opinions and I'll get back to you on it.

**Comment by ilya-konanykhin** [comment]
Thank you for the response, got it.

**Comment by jcn** [comment]
We ended up going a different direction with the gallery and built a custom view in #391. This gave us the flexibility to keep the same page layout, show off the fact that there are additional images when they exist, while also allowing for a lightbox to show the full images.

**Comment by ilya-konanykhin** [comment]
Ok, thanks for the info.

**Pull request closed without merging**
