### PR TITLE
Recent blog post section commented out

### PR DESCRIPTION
**Pull request by emdaniels**
Commented out section on the home page that shows most recent blog posts, per issue #149 on the main project.

### CODE REVIEW

**Comment by jcn** [comment]
@emdaniels I would suggest actually just:

1. Ripping out the code completely (instead of just commenting it out)
2. Removing the inclusion of the `<% content_for :javascript do -%>` at the bottom of the page so the javascript to fetch the feed doesn't fire at all

**Comment by emdaniels** [comment]
Ok- I'll do that

**Comment by emdaniels** [comment]
Hey Jesse- this should be good to go. Is there anything else that needs removing here?

**Comment by jcn** [comment]
Closes #149

**Pull request merged**
